### ISSUE TITLE
Wrong error reporting

### ISSUE THREAD

**Issue by sanastasiou** [marcmo/enforcer#14]
If e..g a line is too long,

this line and all subsequent lines until EOF are also being reported as being too long.

**Comment by Nicoretti** [comment]
Actually this is also true for other errors like mixed whitespace starting with the first encountered TAB all subsequent lines will be marked with an error, even if their are valid.

**Comment by marcmo** [comment]
I tested with 0.14.3 and seems to be ok for me now...subsequent lines are not reported
